<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GO</name>
   <tag></tag>
   <elementGuidId>9cf828e1-3bb7-45ee-80ff-3dd609073514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;subInbox($('#inbox_field').val());&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.primary-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7afa30ee-0d8f-46c0-a4c4-2a964bc45645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn</value>
      <webElementGuid>bbdc583b-8afb-4071-8b3f-f3fc9c3eb6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>subInbox($('#inbox_field').val());</value>
      <webElementGuid>8c2aca1c-bd1a-4809-a6c1-a16ec31bae6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            GO
        </value>
      <webElementGuid>332b367a-4478-4d2c-9aa2-18b926257e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inbox_pane&quot;)/div[1]/div[@class=&quot;wrapper-primary-input medium-w100&quot;]/button[@class=&quot;primary-btn&quot;]</value>
      <webElementGuid>7960bab3-37ba-4c56-a345-ef17d1435ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;subInbox($('#inbox_field').val());&quot;]</value>
      <webElementGuid>d7a07e52-910f-4415-8c7a-faa2148e6c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inbox_pane']/div/div[5]/button</value>
      <webElementGuid>34d02506-0c15-4209-8f05-7292400a1a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public Messages'])[1]/following::button[4]</value>
      <webElementGuid>43f16144-995e-414b-9e33-9847cd4fdcce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Links Found'])[1]/following::button[4]</value>
      <webElementGuid>b3dcfe81-2593-414b-9248-714ff28ee331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[2]/preceding::button[1]</value>
      <webElementGuid>810f8797-32be-46cd-807c-acb60fe2c41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject'])[1]/preceding::button[1]</value>
      <webElementGuid>3ae3c343-a579-4e3c-bcd5-8a21879c0e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GO']/parent::*</value>
      <webElementGuid>2eb33216-b2b8-48b4-a165-82334425a008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>83d636f9-c3bc-4611-ae76-f54056268b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
            GO
        ' or . = '
            GO
        ')]</value>
      <webElementGuid>760c767c-987a-44dd-94e4-56fc9a797b35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
