<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_548437 is your OTP for logging in to the Mango Portal. Please do not share your OTP with anyone for security reasons</name>
   <tag></tag>
   <elementGuidId>8ed78c2f-ed38-4590-9e40-b804be851ee7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/table/tbody/tr/td/table/tbody/tr/td/table[1]/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>81b5183a-5651-4460-92a1-9952f4b4a62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>7db219f5-04cf-4903-8847-bb04083d9a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 548437 is your OTP for logging in to the Mango Portal. Please do not share your OTP with anyone for security reasons. </value>
      <webElementGuid>6eb2aa04-7d29-4508-b920-52414c243942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;em_pd0&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[@class=&quot;em_wrapper&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;em_wrapper&quot;]/tbody[1]/tr[3]/td[1]/table[@class=&quot;em_main_table&quot;]/tbody[1]/tr[2]/td[1]</value>
      <webElementGuid>65a86b2a-3215-4f9e-a411-9b7c466c602e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mailinator/iframe_-- HTML EMAIL BODY --</value>
      <webElementGuid>07a2d3cc-dfe8-4d6c-8f04-c7a5d325f3f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dear Denny ,'])[1]/following::td[1]</value>
      <webElementGuid>4830ffe7-0b52-4dff-a58d-9064420a437d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='click here'])[1]/preceding::td[6]</value>
      <webElementGuid>2115c415-97c5-47cc-bcfb-a665e55e81fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='548437 is your OTP for logging in to the Mango Portal. Please do not share your OTP with anyone for security reasons.']/parent::*</value>
      <webElementGuid>d4c2a19e-fba9-49e7-aab6-2203e2f5603d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr[2]/td</value>
      <webElementGuid>aa83f34b-4dd0-45a0-8aa6-1c0b6a510f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' 548437 is your OTP for logging in to the Mango Portal. Please do not share your OTP with anyone for security reasons. ' or . = ' 548437 is your OTP for logging in to the Mango Portal. Please do not share your OTP with anyone for security reasons. ')]</value>
      <webElementGuid>f5ba49cf-db25-4df6-a647-099fa0c4cf57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
