<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_supportmangosciences.com</name>
   <tag></tag>
   <elementGuidId>5886bfe8-70b9-48b7-bb82-6976f5bf05d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@onclick=&quot;showTheMessage('danny-1662970888-258342282');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9ee360be-d525-498d-b86a-6a3f415c2bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showTheMessage('danny-1662970888-258342282');</value>
      <webElementGuid>9fa68e2b-dfac-410b-b3bb-9f382b7eb1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>if (event.keyCode == 13) { showTheMessage('danny-1662970888-258342282'); }</value>
      <webElementGuid>5d19d3c1-2d0b-4260-967c-a4e9c72f3f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>806a9fc9-52b4-49ca-b220-281a2f5818fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    support@mangosciences.com
                    
                    
                
                </value>
      <webElementGuid>25055bc6-d0a0-4c23-b44e-52bd4215d0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_danny-1662970888-258342282&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>028f406e-d293-4670-90f6-a4c0ec317c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>18a82be2-eb9a-4544-b8f6-9667df1e45a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showTheMessage('danny-1662962664-257963017');</value>
      <webElementGuid>aeae0097-a3f1-4949-bf0d-200f14f53906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>if (event.keyCode == 13) { showTheMessage('danny-1662962664-257963017'); }</value>
      <webElementGuid>3b1a7642-8c02-4c02-90a5-3a3bec52cea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>2edd8794-c3f3-4681-8a46-71fb8207366a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    support@mangosciences.com
                    
                    
                
                </value>
      <webElementGuid>e59e3597-cc66-440a-99e6-09b55bc0c0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_danny-1662962664-257963017&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>ff15c824-1592-4bea-966d-8f81cd705a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6f046906-dc66-43be-886a-309e87a0de4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showTheMessage('danny-1662961808-1281939447');</value>
      <webElementGuid>f80454f5-d18e-4e9b-a7bb-dcd3073dcfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>if (event.keyCode == 13) { showTheMessage('danny-1662961808-1281939447'); }</value>
      <webElementGuid>4662cac2-73cc-42e7-8862-bbec0135ac0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>3d2cb7e2-f1fb-45c2-baa7-b78556ab8c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    support@mangosciences.com
                    
                    
                
                </value>
      <webElementGuid>c080055a-cb0b-4197-bb2d-b268324dc695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_danny-1662961808-1281939447&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>4f09d4ce-0bb5-4378-a110-fde515cab5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d277d5f8-7b3b-4308-9b01-d9b202497af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showTheMessage('denny-1662722549-1274138242');</value>
      <webElementGuid>60fa778b-e64c-403d-ad64-fe9494a0acce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>if (event.keyCode == 13) { showTheMessage('denny-1662722549-1274138242'); }</value>
      <webElementGuid>b8a645a1-b2bc-45db-a169-766ef28342da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>9ad5f28a-b492-4290-8fdb-19cbdc0dda74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    support@mangosciences.com
                    
                    
                
                </value>
      <webElementGuid>ea514449-7e33-4901-b9c9-8cc691fb8ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_denny-1662722549-1274138242&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>b7bf5dfe-9868-4905-a1d5-5a5e33e23215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick=&quot;showTheMessage('danny-1662970888-258342282');&quot;]</value>
      <webElementGuid>c73491e8-4ec6-4545-b152-b47e715b3181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_danny-1662970888-258342282']/td[2]</value>
      <webElementGuid>f0ed7566-dca2-459b-bfa0-63448a360903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Received'])[2]/following::td[2]</value>
      <webElementGuid>3dbfbc64-2e78-4cf3-94f2-485e5cf62960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject'])[1]/following::td[3]</value>
      <webElementGuid>5b86a9bd-5ba6-4e72-beeb-2b23f7d5bc4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your OTP has been generated!'])[1]/preceding::td[1]</value>
      <webElementGuid>e4e52537-40ea-4b31-9129-48d4a12b9633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='just now'])[1]/preceding::td[2]</value>
      <webElementGuid>e3def857-ce5c-455f-a41d-c864e1dfc951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='support@mangosciences.com']/parent::*</value>
      <webElementGuid>c97ef740-a9d2-4097-b837-b25ecb9b29af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr/td[2]</value>
      <webElementGuid>09fd0870-57e3-4eb6-9e00-f6de7b3c11f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                    support@mangosciences.com
                    
                    
                
                ' or . = '
                    support@mangosciences.com
                    
                    
                
                ')]</value>
      <webElementGuid>90963af4-d6da-400b-b419-4d6175eaf4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick=&quot;showTheMessage('danny-1662962664-257963017');&quot;]</value>
      <webElementGuid>59599606-4749-417c-b0c8-6da367f6c4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_danny-1662962664-257963017']/td[2]</value>
      <webElementGuid>622e656b-d85d-47f9-bd79-0ebe0cae67ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@mangosciences.com'])[2]/preceding::td[4]</value>
      <webElementGuid>ececfa2b-186c-4165-8172-44cd8ed0982a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick=&quot;showTheMessage('danny-1662961808-1281939447');&quot;]</value>
      <webElementGuid>527c7f6a-1b10-4fc9-a4ee-5413398f1200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_danny-1662961808-1281939447']/td[2]</value>
      <webElementGuid>5a43f521-3253-483f-b620-bdf0d8452a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick=&quot;showTheMessage('denny-1662722549-1274138242');&quot;]</value>
      <webElementGuid>ffa50b68-a7cf-4ec7-a319-96293e972763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_denny-1662722549-1274138242']/td[2]</value>
      <webElementGuid>1893cb04-e104-4015-a6b7-fabfd5202c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beatrice Edner'])[1]/preceding::td[4]</value>
      <webElementGuid>b08f4a3d-524d-49ea-a0c0-264c5d6a7b55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
