<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Application</name>
   <tag></tag>
   <elementGuidId>cd0949fe-6e15-4ad0-83ba-48cd10c2137d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='custom-side-bar-patient']/div[5]/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b65c23c-0fd4-4942-8aa3-5053b8fd68b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/patient/pbp-program/loan-application</value>
      <webElementGuid>035e29a8-aee0-4f1c-8a88-08e799dfde60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>4dfe0208-83e6-4728-be74-ae586df9efcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Application</value>
      <webElementGuid>6920d6e0-9271-4eec-b891-a3ec03bb6a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-side-bar-patient&quot;)/div[@class=&quot;false accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;multi-level accordion-body&quot;]/div[@class=&quot;flex-column nav&quot;]/div[@class=&quot;false nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>0729c5de-b1df-40ef-b59e-ecf01087034e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-side-bar-patient']/div[5]/div/div/div/div/a</value>
      <webElementGuid>60d2d77c-02ab-401d-9206-00cd146c8c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PBP Program'])[1]/following::a[1]</value>
      <webElementGuid>27b4f862-adb2-4717-b122-61181031783c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinical Notes'])[1]/following::a[2]</value>
      <webElementGuid>979d91e8-2051-4d90-bddd-9f63f5170258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicants'])[1]/preceding::a[1]</value>
      <webElementGuid>4afdb48f-acd7-4cea-8fe8-a863be22e956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/patient/pbp-program/loan-application')]</value>
      <webElementGuid>a8975c67-2950-4de1-aede-6aa25a0b97ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/a</value>
      <webElementGuid>1caad81a-74cd-42fc-b637-9e33ae73de84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/patient/pbp-program/loan-application' and (text() = 'Application' or . = 'Application')]</value>
      <webElementGuid>311e9965-4246-4123-8b17-2f0d1c7b59e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
