<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upload</name>
   <tag></tag>
   <elementGuidId>cc7201ae-8021-43b7-aee8-0d14bb1da0f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div[3]/div/table/tbody/tr/td[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3401676c-d722-4ec9-98d1-510b9bf6d1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-patient-theme-grid </value>
      <webElementGuid>8417f6f7-6988-4394-baef-8eff07db78a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>a0119575-025e-4682-b917-37e9682df69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/div[@class=&quot;right-pane&quot;]/div[2]/div[@class=&quot;item p-4 mt-4 py-3&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;drug-schedule-patient-table-self-pay align-items-center custom-table table&quot;]/tbody[1]/tr[1]/td[@class=&quot;border-0&quot;]/button[@class=&quot;btn-patient-theme-grid&quot;]</value>
      <webElementGuid>8f6dbd10-e1f5-4457-85e9-4fa64c54f618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div[3]/div/table/tbody/tr/td[3]/button</value>
      <webElementGuid>e9dc1c5c-004e-42e0-9030-1d2902ea8fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload']/parent::*</value>
      <webElementGuid>dafc52ed-8c91-43c9-bf25-1e5074ef7c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/button</value>
      <webElementGuid>14090bbe-fe11-4893-9962-85e211f159ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>5a4714d6-fdab-4e86-8290-673869aee06a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
