<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save  Proceed_1</name>
   <tag></tag>
   <elementGuidId>5e938281-8051-42e8-aa6f-9209e19090b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-patient-theme.w-auto.px-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60ee1c05-886d-461d-9812-973a371f71b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d6fd3d58-a4cd-46e7-b512-95b08eacd67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-patient-theme w-auto px-4</value>
      <webElementGuid>a6c5ae80-fea7-47b0-9072-a0975e73e770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save &amp; Proceed</value>
      <webElementGuid>59f71c68-eac0-4623-90f3-e732a3d04056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/div[@class=&quot;right-pane&quot;]/div[@class=&quot;stepper-container-horizontal&quot;]/div[@class=&quot;w-100&quot;]/div[1]/div[@class=&quot;page-container financial-loan p-4 mt-3&quot;]/form[1]/div[@class=&quot;px-0 pb-0 financial-loan pt-0  row&quot;]/div[@class=&quot;d-flex flex-row  mt-2-rem&quot;]/button[@class=&quot;btn-patient-theme w-auto px-4&quot;]</value>
      <webElementGuid>a0466014-90c7-421f-aa02-7643254c734d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>611845ff-70f7-4be7-b33c-1a4fa62a3456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div[2]/div/div/form/div[4]/div[13]/button[2]</value>
      <webElementGuid>b32ef349-0ce7-4cee-97c5-162fbe7b8619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>7bfae953-8f4e-499a-b17e-fb3188152179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::button[1]</value>
      <webElementGuid>689bacfb-c446-4b7f-9c7d-82ebc1cdcff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::button[1]</value>
      <webElementGuid>34b8484b-4b07-4b0d-a7f8-d60e1279d428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save &amp; Proceed']/parent::*</value>
      <webElementGuid>0583bacc-312b-49ca-89a8-9e2b2ec4cafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7809376e-f047-4f72-b659-e463dc542daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Save &amp; Proceed' or . = 'Save &amp; Proceed')]</value>
      <webElementGuid>34911083-436d-42c9-8009-e92b1f6f3357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
