<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>439cb0c1-bca5-4c5d-b23d-14011d234dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mt-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div/form/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2cd91ff5-5f7b-4ad9-9974-45af5c53815b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4</value>
      <webElementGuid>c2877587-0253-4b5f-89c4-7bb4ca1679e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>ff32cb81-d16b-4612-b23b-be094b90011c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;login-main&quot;]/div[2]/div[@class=&quot;reg-container self d-flex justify-content-center align-items-center  container&quot;]/div[@class=&quot;reg-box d-flex flex-column&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/button[@class=&quot;mt-4&quot;]</value>
      <webElementGuid>218b0728-5a98-482b-a55c-9dda62f38865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ed5fc80-06d3-4a9e-a2c9-8096f8bd4a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3</value>
      <webElementGuid>297fa4f5-636d-4e4c-9007-c2c4a854b165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>951a1539-a318-4e1d-b5dc-0b8f3750fd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;login-main-registration&quot;]/div[@class=&quot;item-position&quot;]/div[@class=&quot;reg-container&quot;]/div[@class=&quot;m-auto reg-box&quot;]/form[1]/button[@class=&quot;mt-3&quot;]</value>
      <webElementGuid>7e84aa7c-8497-4f1e-8bf3-ca100bb20a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7dcdbda5-5661-4d81-8197-3d6359f9ad1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3</value>
      <webElementGuid>9adefae8-9173-47bb-9d8c-41ce46382112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>360fecd2-2214-4183-9c3f-43b0913b44f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;login-main-registration&quot;]/div[@class=&quot;item-position&quot;]/div[@class=&quot;reg-container&quot;]/div[@class=&quot;m-auto reg-box&quot;]/form[1]/button[@class=&quot;mt-3&quot;]</value>
      <webElementGuid>c1384e47-c06a-49ce-8f02-79d27ef339db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>676f77e0-4dfe-4cca-af84-30cab0543834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3</value>
      <webElementGuid>9b1db09d-552e-4f33-bf53-ae7737ef115b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>ee036fcc-bb4f-450f-9cb5-fa7e723d93b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;login-main-registration&quot;]/div[@class=&quot;item-position&quot;]/div[@class=&quot;reg-container&quot;]/div[@class=&quot;m-auto reg-box&quot;]/form[1]/button[@class=&quot;mt-3&quot;]</value>
      <webElementGuid>c1f7c7c1-20b3-4ee4-a786-bdcee4fb1a32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/div[2]/div/button</value>
      <webElementGuid>e0fbb266-838e-4aca-9037-ba08a3fcbefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I confirm that I have read and understood the terms of use of Mango Cancer Care PBP programme.'])[1]/following::button[1]</value>
      <webElementGuid>f0732b21-4310-4958-9828-fa182905660c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>5893fb60-4e52-4dae-adbc-02ed1f3c0b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>da03e5b8-e2fa-4311-9b4b-14e62512080c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>c74b1a9a-0025-4a53-a970-9c80c49f5761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]/div/form/button</value>
      <webElementGuid>6fc00a71-d0f6-47ed-bd45-cd0f64f1d833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::button[1]</value>
      <webElementGuid>b7de9e71-a08b-4b7c-8d7c-0297acdc5945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Querent PBP'])[1]/following::button[1]</value>
      <webElementGuid>344013a0-c1e8-4c43-9d3f-43bc9b857b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Here'])[1]/preceding::button[1]</value>
      <webElementGuid>1b963677-046f-4a3e-bf1f-957cd5c2b7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::button[1]</value>
      <webElementGuid>18d2a882-0b3c-419c-bf75-e78e27bc2722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
