<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Designation</name>
   <tag></tag>
   <elementGuidId>a730770a-b4b1-461e-a55b-327f32c95c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div[2]/div/div/form/div[4]/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f77917e-f6c6-4106-bcba-00f7353aee7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-12 col-md-6 col-lg-4 mb-2  col</value>
      <webElementGuid>98711cf2-0f30-42de-98f1-43c08a77692f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Designation :</value>
      <webElementGuid>1217f375-7527-43b6-a479-7ea29cfba6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/div[@class=&quot;right-pane&quot;]/div[@class=&quot;stepper-container-horizontal&quot;]/div[@class=&quot;w-100&quot;]/div[1]/div[@class=&quot;page-container financial-loan p-4 mt-3&quot;]/form[1]/div[@class=&quot;px-0 pb-0 financial-loan pt-0  row&quot;]/div[@class=&quot;col-sm-12 col-md-6 col-lg-4 mb-2  col&quot;]</value>
      <webElementGuid>cae2f746-a1e7-416c-ad34-cdbaff5eae76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div[2]/div/div/form/div[4]/div[6]</value>
      <webElementGuid>2aac22d0-9568-44d4-a4a3-9595366d45b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average Annual Income'])[1]/preceding::div[1]</value>
      <webElementGuid>8b9bc375-7d1d-4242-96f2-9935eba3574d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[6]</value>
      <webElementGuid>4784d3ec-a2dd-4f67-b434-341337e3fdf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Designation :' or . = 'Designation :')]</value>
      <webElementGuid>b95f3a23-bccb-4b1a-b310-a438798af432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
