<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fill All Fields to Complete Your Profil_0b14e0</name>
   <tag></tag>
   <elementGuidId>41f4300d-ac95-4868-8e6c-d1bf38552198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab2cbc28-7adf-4547-aed3-41bef01629d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>5f1faa66-2a3f-4c04-a211-243a5cb46756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fill All Fields to Complete Your ProfilePersonal Details:GenderMaleFemaleAddress Information :Select CountryIndiaSelect StateAndaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra and Nagar Haveli and Daman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest BengalSelect CityAmbalaAsandhAteli MandiBahadurgarhBara UchanaBarwalaBawalBeri KhasBhiwaniBilaspurBuriyaCharkhi DadriChhachhrauliDabwaliDharuheraEllenabadFaridabadFaridabad DistrictFarrukhnagarFatehabadFatehabad DistrictFirozpur JhirkaGharaundaGohanaGorakhpurGurgaonHansiHasanpurHisarHodalInda ChhoiIndriJagadhriJakhalJhajjarJindKaithalKalanaurKalanwaliKanina KhasKarnalKharkhaudaKheri SamplaKurukshetraLadwaLoharuMahamMahendragarhMandholi KalanMustafabadNarayangarhNarnaulNarnaundNarwanaNilokheriNuhPalwalPanchkulaPanipatPataudiPehowaPinjaurPunahanaPundriRadaurRaniaRatiaRewariRewari DistrictRohtakSafidonSamalkhaShadipur JulanaShahabadSirsaSohnaSonipatTaoruThanesarTohanaToshamUklanaYamunanagarClick to copy Permanent Address dataSelect CountryIndiaSelect StateAndaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra and Nagar Haveli and Daman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest BengalSelect CityAmbalaAsandhAteli MandiBahadurgarhBara UchanaBarwalaBawalBeri KhasBhiwaniBilaspurBuriyaCharkhi DadriChhachhrauliDabwaliDharuheraEllenabadFaridabadFaridabad DistrictFarrukhnagarFatehabadFatehabad DistrictFirozpur JhirkaGharaundaGohanaGorakhpurGurgaonHansiHasanpurHisarHodalInda ChhoiIndriJagadhriJakhalJhajjarJindKaithalKalanaurKalanwaliKanina KhasKarnalKharkhaudaKheri SamplaKurukshetraLadwaLoharuMahamMahendragarhMandholi KalanMustafabadNarayangarhNarnaulNarnaundNarwanaNilokheriNuhPalwalPanchkulaPanipatPataudiPehowaPinjaurPunahanaPundriRadaurRaniaRatiaRewariRewari DistrictRohtakSafidonSamalkhaShadipur JulanaShahabadSirsaSohnaSonipatTaoruThanesarTohanaToshamUklanaYamunanagarHospital Details:Select DiagnosisNon-small Cell Lung CancerBreast CancerHead &amp; Neck CancerMedication NameTagrisso-OsimertinibDBRAND-DGENERICSelect Hospital Aster CMI  Aster MIMS  Aster Medcity  sdgfd  sdsfds  MAX  Apollo hyd  Max delhi  Apollo Chennai Select DoctorFinancial Information :Read Terms of Use I confirm that I have read and understood the terms of use of Mango Cancer Care PBP programme.Next</value>
      <webElementGuid>79a71914-32b4-4445-9253-cb3009485c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)</value>
      <webElementGuid>bdd74383-141f-453a-bca0-6af7c11766ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='root']</value>
      <webElementGuid>7cd0d208-45e6-413f-8f98-64240c961ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>5327d9e4-1bd6-4784-a036-83b291b7a17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'root' and (text() = 'Fill All Fields to Complete Your ProfilePersonal Details:GenderMaleFemaleAddress Information :Select CountryIndiaSelect StateAndaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra and Nagar Haveli and Daman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest BengalSelect CityAmbalaAsandhAteli MandiBahadurgarhBara UchanaBarwalaBawalBeri KhasBhiwaniBilaspurBuriyaCharkhi DadriChhachhrauliDabwaliDharuheraEllenabadFaridabadFaridabad DistrictFarrukhnagarFatehabadFatehabad DistrictFirozpur JhirkaGharaundaGohanaGorakhpurGurgaonHansiHasanpurHisarHodalInda ChhoiIndriJagadhriJakhalJhajjarJindKaithalKalanaurKalanwaliKanina KhasKarnalKharkhaudaKheri SamplaKurukshetraLadwaLoharuMahamMahendragarhMandholi KalanMustafabadNarayangarhNarnaulNarnaundNarwanaNilokheriNuhPalwalPanchkulaPanipatPataudiPehowaPinjaurPunahanaPundriRadaurRaniaRatiaRewariRewari DistrictRohtakSafidonSamalkhaShadipur JulanaShahabadSirsaSohnaSonipatTaoruThanesarTohanaToshamUklanaYamunanagarClick to copy Permanent Address dataSelect CountryIndiaSelect StateAndaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra and Nagar Haveli and Daman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest BengalSelect CityAmbalaAsandhAteli MandiBahadurgarhBara UchanaBarwalaBawalBeri KhasBhiwaniBilaspurBuriyaCharkhi DadriChhachhrauliDabwaliDharuheraEllenabadFaridabadFaridabad DistrictFarrukhnagarFatehabadFatehabad DistrictFirozpur JhirkaGharaundaGohanaGorakhpurGurgaonHansiHasanpurHisarHodalInda ChhoiIndriJagadhriJakhalJhajjarJindKaithalKalanaurKalanwaliKanina KhasKarnalKharkhaudaKheri SamplaKurukshetraLadwaLoharuMahamMahendragarhMandholi KalanMustafabadNarayangarhNarnaulNarnaundNarwanaNilokheriNuhPalwalPanchkulaPanipatPataudiPehowaPinjaurPunahanaPundriRadaurRaniaRatiaRewariRewari DistrictRohtakSafidonSamalkhaShadipur JulanaShahabadSirsaSohnaSonipatTaoruThanesarTohanaToshamUklanaYamunanagarHospital Details:Select DiagnosisNon-small Cell Lung CancerBreast CancerHead &amp; Neck CancerMedication NameTagrisso-OsimertinibDBRAND-DGENERICSelect Hospital Aster CMI  Aster MIMS  Aster Medcity  sdgfd  sdsfds  MAX  Apollo hyd  Max delhi  Apollo Chennai Select DoctorFinancial Information :Read Terms of Use I confirm that I have read and understood the terms of use of Mango Cancer Care PBP programme.Next' or . = 'Fill All Fields to Complete Your ProfilePersonal Details:GenderMaleFemaleAddress Information :Select CountryIndiaSelect StateAndaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra and Nagar Haveli and Daman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest BengalSelect CityAmbalaAsandhAteli MandiBahadurgarhBara UchanaBarwalaBawalBeri KhasBhiwaniBilaspurBuriyaCharkhi DadriChhachhrauliDabwaliDharuheraEllenabadFaridabadFaridabad DistrictFarrukhnagarFatehabadFatehabad DistrictFirozpur JhirkaGharaundaGohanaGorakhpurGurgaonHansiHasanpurHisarHodalInda ChhoiIndriJagadhriJakhalJhajjarJindKaithalKalanaurKalanwaliKanina KhasKarnalKharkhaudaKheri SamplaKurukshetraLadwaLoharuMahamMahendragarhMandholi KalanMustafabadNarayangarhNarnaulNarnaundNarwanaNilokheriNuhPalwalPanchkulaPanipatPataudiPehowaPinjaurPunahanaPundriRadaurRaniaRatiaRewariRewari DistrictRohtakSafidonSamalkhaShadipur JulanaShahabadSirsaSohnaSonipatTaoruThanesarTohanaToshamUklanaYamunanagarClick to copy Permanent Address dataSelect CountryIndiaSelect StateAndaman and Nicobar IslandsAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra and Nagar Haveli and Daman and DiuDelhiGoaGujaratHaryanaHimachal PradeshJammu and KashmirJharkhandKarnatakaKeralaLadakhLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOdishaPuducherryPunjabRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest BengalSelect CityAmbalaAsandhAteli MandiBahadurgarhBara UchanaBarwalaBawalBeri KhasBhiwaniBilaspurBuriyaCharkhi DadriChhachhrauliDabwaliDharuheraEllenabadFaridabadFaridabad DistrictFarrukhnagarFatehabadFatehabad DistrictFirozpur JhirkaGharaundaGohanaGorakhpurGurgaonHansiHasanpurHisarHodalInda ChhoiIndriJagadhriJakhalJhajjarJindKaithalKalanaurKalanwaliKanina KhasKarnalKharkhaudaKheri SamplaKurukshetraLadwaLoharuMahamMahendragarhMandholi KalanMustafabadNarayangarhNarnaulNarnaundNarwanaNilokheriNuhPalwalPanchkulaPanipatPataudiPehowaPinjaurPunahanaPundriRadaurRaniaRatiaRewariRewari DistrictRohtakSafidonSamalkhaShadipur JulanaShahabadSirsaSohnaSonipatTaoruThanesarTohanaToshamUklanaYamunanagarHospital Details:Select DiagnosisNon-small Cell Lung CancerBreast CancerHead &amp; Neck CancerMedication NameTagrisso-OsimertinibDBRAND-DGENERICSelect Hospital Aster CMI  Aster MIMS  Aster Medcity  sdgfd  sdsfds  MAX  Apollo hyd  Max delhi  Apollo Chennai Select DoctorFinancial Information :Read Terms of Use I confirm that I have read and understood the terms of use of Mango Cancer Care PBP programme.Next')]</value>
      <webElementGuid>087f020f-edda-4b7e-8409-035b4e291c93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
