<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BackSave  Proceed</name>
   <tag></tag>
   <elementGuidId>e6576434-4c81-474f-9756-a3ebfceea57a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.flex-row.mt-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div[2]/form/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c99aef2-47a2-4446-8f67-108ba5351d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex flex-row  mt-4</value>
      <webElementGuid>3352a645-a949-46df-a53d-90c5bf824c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BackSave &amp; Proceed</value>
      <webElementGuid>723a6940-2d0f-4baf-8100-cabf0a67088b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/div[@class=&quot;right-pane&quot;]/div[@class=&quot;stepper-container-horizontal&quot;]/div[@class=&quot;w-100&quot;]/form[1]/div[@class=&quot;d-flex flex-row  mt-4&quot;]</value>
      <webElementGuid>58f62c92-7525-4e11-ba67-59f2dd90b03b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div[2]/form/div[2]</value>
      <webElementGuid>9b8a0ea2-1dfc-4e0b-b7b2-8e966e48c637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View PBP Schedule'])[1]/following::div[4]</value>
      <webElementGuid>12134fbf-5c1b-4df3-9acf-872c8017c6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1820040.00*'])[1]/following::div[6]</value>
      <webElementGuid>9d67d9f4-c5e1-41fc-bb4a-26be80279c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>f86ce5da-01b1-4f4c-a29f-fb1407ae0c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BackSave &amp; Proceed' or . = 'BackSave &amp; Proceed')]</value>
      <webElementGuid>adec08f2-ee18-46d6-a956-e9253028c13d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
