<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form-control</name>
   <tag></tag>
   <elementGuidId>26e69231-c2d8-48a4-9f71-5be8ab5440d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b57af15-0a7a-4c40-a776-1b2b02f15024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e4e8534-13ee-4234-81e6-443f77f34687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0b12d444-4fd9-4b6f-9c1e-b070adc4141a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/div[@class=&quot;right-pane&quot;]/div[@class=&quot;stepper-container-horizontal&quot;]/div[@class=&quot;w-100&quot;]/div[1]/div[@class=&quot;page-container financial-loan p-4 mt-3&quot;]/form[1]/div[@class=&quot;px-0 pb-3 financial-loan pt-0  row&quot;]/div[@class=&quot;col-sm-12 col-md-6 col-lg-4 mb-2  col&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>9d95bcec-5968-41ca-9611-0cdc20b629a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>5724367f-ef94-4e5f-ae51-4375949714d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div[2]/div/div/form/div[2]/div/input</value>
      <webElementGuid>0fe7f8a3-37c2-4f53-8075-3739393f43b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>240e385d-d86b-4426-9c1b-32c48811acd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>4e19d66c-5460-4784-828d-93586a144ba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
