<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hospital Details_medical-record-name</name>
   <tag></tag>
   <elementGuidId>3be1a908-b834-4de4-a4f5-1949080689b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#medical-record-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='medical-record-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0070567c-aacc-49a4-abc6-b75d8fb9362b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Medical Record Number</value>
      <webElementGuid>f50ce0db-4e25-4ba5-a0cf-7e9933f71bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25ef3683-f6aa-4d9c-b0e6-080c235f7288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>medical-record-name</value>
      <webElementGuid>61825510-4e2a-4d97-bc67-6b133265fc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b89aa68a-0964-4196-98c7-b7f85e40f672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;medical-record-name&quot;)</value>
      <webElementGuid>dd0a5de7-0b30-40d7-9729-6ab0d8f33573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='medical-record-name']</value>
      <webElementGuid>0f08d01e-fd7e-46bc-bb0a-0be4c32a9d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/fieldset[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>e3e419eb-d118-47aa-8bc4-cc9f49aba00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>a83e86cc-1ee8-468b-9979-0b98f31f5772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Medical Record Number' and @type = 'text' and @id = 'medical-record-name']</value>
      <webElementGuid>d7d3c333-41b4-480b-8967-0ef7f3e2e187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
