<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Register_newUserEmail</name>
   <tag></tag>
   <elementGuidId>12ea336a-e26e-4a25-807d-97ce2736b10d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newUserEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newUserEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dae09d8-5ec3-41cd-abb5-b26a3bba007b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>9e2214a0-2ed2-4eab-9965-14b292598435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6541f4f3-4f1e-43f6-b088-97e3c42b3ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newUserEmail</value>
      <webElementGuid>23d5801f-583a-4ed9-9b41-71e40f2f33bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3 p-3 form-control</value>
      <webElementGuid>d1eaebed-097f-4900-8894-8591eb4959fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;login-main-registration&quot;]/div[@class=&quot;item-position&quot;]/div[@class=&quot;reg-container&quot;]/div[@class=&quot;m-auto reg-box&quot;]/form[1]/div[1]/input[@id=&quot;newUserEmail&quot;]</value>
      <webElementGuid>f8c46e1e-b6ce-42e5-a693-d22d8447f4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>134556b7-2bc2-419b-b73c-425856c86979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>3ce8ddc3-4310-407a-8ee0-1aa151557f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>328f335f-8f20-4325-952f-d34d65660b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newUserEmail</value>
      <webElementGuid>76814494-ce25-402b-af62-6cb99c83846f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3 p-3 form-control</value>
      <webElementGuid>1279fe5e-c616-4fbc-9173-d77d3173c598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;login-main-registration&quot;]/div[@class=&quot;item-position&quot;]/div[@class=&quot;reg-container&quot;]/div[@class=&quot;m-auto reg-box&quot;]/form[1]/div[1]/input[@id=&quot;newUserEmail&quot;]</value>
      <webElementGuid>fe390231-6479-46f1-b297-3f1e2a264ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>badf35f5-d635-4593-8787-6abc389c6428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>e6854898-39fa-4c94-8a43-ade020bae193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f18e356d-3c9d-4dbf-9646-5a349692f0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newUserEmail</value>
      <webElementGuid>6d4aba9b-8fde-44f9-8f4c-71dc9b9b4dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3 p-3 form-control</value>
      <webElementGuid>19ed6163-f575-4a9c-b27b-1a7293b19b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;login-main-registration&quot;]/div[@class=&quot;item-position&quot;]/div[@class=&quot;reg-container&quot;]/div[@class=&quot;m-auto reg-box&quot;]/form[1]/div[1]/input[@id=&quot;newUserEmail&quot;]</value>
      <webElementGuid>a8c8de24-e72c-4555-b0a7-7016b5fc844f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newUserEmail']</value>
      <webElementGuid>814136f7-a4da-4973-a3de-af2cd60d00ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]/div/form/div/input</value>
      <webElementGuid>8a4cec37-9615-42ef-9029-9579f41eabf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>52b39e2d-f77c-4151-943a-51f7f3d1ae67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Name' and @type = 'text' and @id = 'newUserEmail']</value>
      <webElementGuid>92fad93b-9f30-49ff-a3d8-2f4dd5c1f70a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
