<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Self Pay_radio</name>
   <tag></tag>
   <elementGuidId>324f568a-791b-4334-bc76-99b81a0a5158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='radio'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04901577-8cbc-4fbf-bf03-d1b4da29a548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b8ca9111-dd48-435e-b8a0-c69eedb59eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b55594ce-d12a-43ec-890c-15d0c87a435a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a998ae24-4480-48a9-9cc9-5e885d480693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LOAN_WITH_FINANCIAL_ASSISTANCE</value>
      <webElementGuid>f9c29563-31c9-4f18-9f6f-00d712f63fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/div[@class=&quot;right-pane&quot;]/div[@class=&quot;stepper-container-horizontal&quot;]/div[@class=&quot;w-100&quot;]/div[1]/div[@class=&quot;page-container loan-app mt-3&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;col-sm-10&quot;]/div[@class=&quot;pretty-radio&quot;]/input[@class=&quot;radio&quot;]</value>
      <webElementGuid>841d65ba-f696-4fdb-9973-f86388d352c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='radio'])[2]</value>
      <webElementGuid>b078c5f3-9869-4c90-8f82-4fab08d14c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>da8f6c2e-b300-496f-a021-b25d49ce822e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>45bed904-eecc-4d91-805f-ae1babb9bf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'radio']</value>
      <webElementGuid>e72f0d5a-da3f-411f-bd3d-027db2e2fb2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
