<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Financial Information_formBasicCheckbox</name>
   <tag></tag>
   <elementGuidId>4b8d7640-0d82-4cb2-96ca-2ad62144b11b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formBasicCheckbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formBasicCheckbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba1a736c-e21a-4f79-bf68-4fe914c002e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1fb0e745-a763-4283-8a99-3ba3b15c3984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formBasicCheckbox</value>
      <webElementGuid>964732e1-06f4-4bd0-817b-2224863acd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b9cca411-6974-4da8-a023-e8265582063b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formBasicCheckbox&quot;)</value>
      <webElementGuid>d965f364-f278-42e4-9e6a-1028a5c7f2ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formBasicCheckbox']</value>
      <webElementGuid>ed0001ef-589f-49c3-86e3-d10d47c341fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/div/div/div/div/div/input</value>
      <webElementGuid>1021a69f-0e4c-4b17-895b-f788f361c4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>ee9a895f-f82b-4f01-b547-cdc686e47c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'formBasicCheckbox']</value>
      <webElementGuid>8c53021f-8f6d-4463-b152-4464a6b2092a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
