<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Financial Information_pan-number</name>
   <tag></tag>
   <elementGuidId>402a0e5e-9a3f-4436-988d-4f492901089e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pan-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pan-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b6af00c-9b3e-4599-94d0-655112350d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PAN Number</value>
      <webElementGuid>a304db29-d53d-4b10-83c2-2d971a6fbc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>efe75d65-7271-4045-8e21-de017e75de0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pan-number</value>
      <webElementGuid>28426689-0bec-4a3f-8856-c78080e5aad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fe84cf48-6744-489c-8ddb-7d48fe39ea86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pan-number&quot;)</value>
      <webElementGuid>5d73dc9e-d6fc-45cf-b817-f79fe0f3e955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pan-number']</value>
      <webElementGuid>215e5b8d-90d8-4f3f-8f43-625787eb6e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/fieldset[4]/div/div/div/input</value>
      <webElementGuid>a0cc206f-df1a-4870-8e15-5f808a32b53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/div/div/input</value>
      <webElementGuid>3a003e62-ba69-4ee6-a8e7-ac15c43bd9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'PAN Number' and @type = 'text' and @id = 'pan-number']</value>
      <webElementGuid>13b26fb2-02e4-4a1c-9bf5-d3192707c157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
