<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Medication NameTagrisso-OsimertinibD_c55ba4</name>
   <tag></tag>
   <elementGuidId>4ae200c9-c32c-4ea3-94ae-32f0661eadd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Drug-Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Drug-Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>02a1de6c-de56-46a3-8b11-e3f9c738936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Medication Name</value>
      <webElementGuid>d5a4e9e4-9a4c-4011-b060-5e5da2ab2669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Drug-Name</value>
      <webElementGuid>82e47169-bd52-4960-89ac-a84042356de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>62a40fc6-a256-45ed-8a03-f1a6586ed261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medication NameTagrisso-OsimertinibDBRAND-DGENERIC</value>
      <webElementGuid>7e2306fe-8839-4610-ab3f-41a71d4b9a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Drug-Name&quot;)</value>
      <webElementGuid>10dc4def-b53a-490b-8b90-dcc46cd9aa02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Drug-Name']</value>
      <webElementGuid>e8d7c09a-f2d2-4786-beab-12c4f13fbda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/fieldset[3]/div/div[2]/div/select</value>
      <webElementGuid>01fe60a0-870d-4fb9-9656-aa52e7e2b695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospital Details:'])[1]/following::select[2]</value>
      <webElementGuid>32448346-3d1e-4351-bbfa-fc6a389c5147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to copy Permanent Address data'])[1]/following::select[5]</value>
      <webElementGuid>700f1782-cf66-4456-afef-463ba80dcac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I confirm that I have read and understood the terms of use of Mango Cancer Care PBP programme.'])[1]/preceding::select[3]</value>
      <webElementGuid>ef8abd1b-5dd2-4ad6-b6d9-e26b44abdfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div[2]/div/select</value>
      <webElementGuid>cefdc94f-d7a7-48d8-aac6-ec68ae4ef349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Medication Name' and @id = 'Drug-Name' and (text() = 'Medication NameTagrisso-OsimertinibDBRAND-DGENERIC' or . = 'Medication NameTagrisso-OsimertinibDBRAND-DGENERIC')]</value>
      <webElementGuid>fb60101c-5bf0-4145-ad2a-7b63c43466cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
