<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Doctor Ganesh  Naik  Sunny  m_418ce3</name>
   <tag></tag>
   <elementGuidId>9a716d2f-6de5-4c64-b14b-19029d6c85c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Doctor-Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Doctor-Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>78e41437-8077-4f80-a3e0-ca0360081518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Doctor Name</value>
      <webElementGuid>c9af51b3-d168-4add-9dde-5b7db1001149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Doctor-Name</value>
      <webElementGuid>26eef52d-1c36-4af9-bccb-eebf95098ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>72fe82f9-8f1c-4312-8389-48f4cf18bd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Doctor Ganesh  Naik  Sunny  mathew  Alex  Dr  Doctor replicate issue  Doctor  6006  Doctor  Dr7006  Dr. Miracle Chaudhary  Ramesh  Murthy  asdsad  sdadsa  Rakesh  Nayak  Jeevan  Jan  Duniya gol hai  adad  satish  Rajesh  G  Suresh  H  New Doc ada  Vijay Agarwal N/A  Aditya Murali N N/A  Vikram Kekatpure N/A  Kumara Swamy N/A  Vikram Maiya N/A  Girish G N/A  Darshan Patil N/A  Girish Shetkar N/A  Girish Shetkar  Vijay Agarwal  Aditya Murali N  D1   Agarwal  D8   Shetkar  D15   Charles  D22   KT  D29   Rajan  D36   Dodagoudar  D43   Sharma  D50   Aagre  D57   Pani  D64   Chaudhary  D71   Gupta  D78   Chakravarthy  D85  D92   Srinivasan  D99   Rao  D106   Bansal  D113   Vaishaimpayan  D120   R  D127   Nair  D134   Mohanty  D141   Singhal  D148   Pasha  D155   Saggu  D162   Bhandari  D169   Reddy  D176   Saha  D183   Kar  D190   Das  D197  D204   P  D211   Narayanan  D218   Bharatwaj V  D225   De  D232   Mathew  D239   M  D246  D253   Dash  D260   Masodkar  D267   Reddy  D274   Goswami  D281   Acharyya  D288  D295   Chandrasekhar  D302   Ilangovan  Test-1 doc-1  test-2 doc-2  DR008   Shetkar  DR0008   Shetkar  DR2008   Shetkar  uiui   Shetkar  No email 9   Shetkar </value>
      <webElementGuid>389ec4ef-fae1-4c38-b215-2758f2ff4a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Doctor-Name&quot;)</value>
      <webElementGuid>b65c7673-9948-4a09-bbf7-8c8e44a2d993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Doctor-Name']</value>
      <webElementGuid>08c516da-217a-442b-96c2-db14478b51ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/fieldset[3]/div[2]/div/div/select</value>
      <webElementGuid>5083e58d-b3db-4c5a-95ad-fc3a08ebd1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospital Details:'])[1]/following::select[4]</value>
      <webElementGuid>7f1d022f-8ef9-4b5a-a06c-252bdee8473b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to copy Permanent Address data'])[1]/following::select[7]</value>
      <webElementGuid>0a3a18fd-6751-45a9-943b-6315fdbc9961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I confirm that I have read and understood the terms of use of Mango Cancer Care PBP programme.'])[1]/preceding::select[1]</value>
      <webElementGuid>141b8f00-99ef-4b3f-a4c0-17f6285abc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[2]/div/div/select</value>
      <webElementGuid>928922c7-ada5-4257-a11b-bda3cfb4838b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Doctor Name' and @id = 'Doctor-Name' and (text() = 'Select Doctor Ganesh  Naik  Sunny  mathew  Alex  Dr  Doctor replicate issue  Doctor  6006  Doctor  Dr7006  Dr. Miracle Chaudhary  Ramesh  Murthy  asdsad  sdadsa  Rakesh  Nayak  Jeevan  Jan  Duniya gol hai  adad  satish  Rajesh  G  Suresh  H  New Doc ada  Vijay Agarwal N/A  Aditya Murali N N/A  Vikram Kekatpure N/A  Kumara Swamy N/A  Vikram Maiya N/A  Girish G N/A  Darshan Patil N/A  Girish Shetkar N/A  Girish Shetkar  Vijay Agarwal  Aditya Murali N  D1   Agarwal  D8   Shetkar  D15   Charles  D22   KT  D29   Rajan  D36   Dodagoudar  D43   Sharma  D50   Aagre  D57   Pani  D64   Chaudhary  D71   Gupta  D78   Chakravarthy  D85  D92   Srinivasan  D99   Rao  D106   Bansal  D113   Vaishaimpayan  D120   R  D127   Nair  D134   Mohanty  D141   Singhal  D148   Pasha  D155   Saggu  D162   Bhandari  D169   Reddy  D176   Saha  D183   Kar  D190   Das  D197  D204   P  D211   Narayanan  D218   Bharatwaj V  D225   De  D232   Mathew  D239   M  D246  D253   Dash  D260   Masodkar  D267   Reddy  D274   Goswami  D281   Acharyya  D288  D295   Chandrasekhar  D302   Ilangovan  Test-1 doc-1  test-2 doc-2  DR008   Shetkar  DR0008   Shetkar  DR2008   Shetkar  uiui   Shetkar  No email 9   Shetkar ' or . = 'Select Doctor Ganesh  Naik  Sunny  mathew  Alex  Dr  Doctor replicate issue  Doctor  6006  Doctor  Dr7006  Dr. Miracle Chaudhary  Ramesh  Murthy  asdsad  sdadsa  Rakesh  Nayak  Jeevan  Jan  Duniya gol hai  adad  satish  Rajesh  G  Suresh  H  New Doc ada  Vijay Agarwal N/A  Aditya Murali N N/A  Vikram Kekatpure N/A  Kumara Swamy N/A  Vikram Maiya N/A  Girish G N/A  Darshan Patil N/A  Girish Shetkar N/A  Girish Shetkar  Vijay Agarwal  Aditya Murali N  D1   Agarwal  D8   Shetkar  D15   Charles  D22   KT  D29   Rajan  D36   Dodagoudar  D43   Sharma  D50   Aagre  D57   Pani  D64   Chaudhary  D71   Gupta  D78   Chakravarthy  D85  D92   Srinivasan  D99   Rao  D106   Bansal  D113   Vaishaimpayan  D120   R  D127   Nair  D134   Mohanty  D141   Singhal  D148   Pasha  D155   Saggu  D162   Bhandari  D169   Reddy  D176   Saha  D183   Kar  D190   Das  D197  D204   P  D211   Narayanan  D218   Bharatwaj V  D225   De  D232   Mathew  D239   M  D246  D253   Dash  D260   Masodkar  D267   Reddy  D274   Goswami  D281   Acharyya  D288  D295   Chandrasekhar  D302   Ilangovan  Test-1 doc-1  test-2 doc-2  DR008   Shetkar  DR0008   Shetkar  DR2008   Shetkar  uiui   Shetkar  No email 9   Shetkar ')]</value>
      <webElementGuid>ccd87fe2-748c-4d01-92c6-1e1b6c707525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
