<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Hospital Aster CMI  Aster MIM_737570</name>
   <tag></tag>
   <elementGuidId>04890642-18a8-44cd-afd0-be726d56cc43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Hospital-Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Hospital-Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67449782-996c-4dda-b51f-c16288fbacd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Hospital Name</value>
      <webElementGuid>86e5096d-077c-4131-9abb-67738e3f1b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Hospital-Name</value>
      <webElementGuid>7b39ded3-5323-4721-a3ae-cc52f2de01b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3f98a60-496c-4198-a0d9-0d0c68eca258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Hospital Aster CMI  Aster MIMS  Aster Medcity  sdgfd  sdsfds  MAX  Apollo hyd  Max delhi  Apollo Chennai </value>
      <webElementGuid>20641520-3cc8-4994-b3ad-ee12efd450ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Hospital-Name&quot;)</value>
      <webElementGuid>a61725e2-c314-4488-bb6a-6b737ce13c50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Hospital-Name']</value>
      <webElementGuid>7fd6de76-587c-4b61-9746-ad06c49d79de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/fieldset[3]/div/div[3]/div/select</value>
      <webElementGuid>2c1e3092-7611-4fd0-ba0b-69a52427b839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospital Details:'])[1]/following::select[3]</value>
      <webElementGuid>55a0b686-f987-4f36-a0c6-5a3433ddef28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to copy Permanent Address data'])[1]/following::select[6]</value>
      <webElementGuid>8516e168-b033-4037-946e-ce134ecd6c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I confirm that I have read and understood the terms of use of Mango Cancer Care PBP programme.'])[1]/preceding::select[2]</value>
      <webElementGuid>73a00489-ea4b-4d73-9b0c-0adf90ca0bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>f4b5f34b-578b-410f-b1dd-b00014c76194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Hospital Name' and @id = 'Hospital-Name' and (text() = 'Select Hospital Aster CMI  Aster MIMS  Aster Medcity  sdgfd  sdsfds  MAX  Apollo hyd  Max delhi  Apollo Chennai ' or . = 'Select Hospital Aster CMI  Aster MIMS  Aster Medcity  sdgfd  sdsfds  MAX  Apollo hyd  Max delhi  Apollo Chennai ')]</value>
      <webElementGuid>50e78922-f312-4ece-af88-8ac91da2e8a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
