<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select DiagnosisNon-small Cell Lung _e09e88</name>
   <tag></tag>
   <elementGuidId>10a4b5c9-e2a6-4d0a-aa7c-cfdcdb3de116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#diagnosis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='diagnosis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>72f65572-b497-4f97-8670-df64898bedb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>diagnosis</value>
      <webElementGuid>9486152a-2200-4109-bfa5-32f2a75944c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2c23ff1f-ada7-40a8-a59e-c5610cb05967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select DiagnosisNon-small Cell Lung CancerBreast CancerHead &amp; Neck Cancer</value>
      <webElementGuid>791d66cf-2222-4770-adbc-4681791c046a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diagnosis&quot;)</value>
      <webElementGuid>1f355a85-3089-4c74-ac16-09473917f23e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='diagnosis']</value>
      <webElementGuid>bef3d921-69d0-4705-87af-2558cb31bb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/fieldset[3]/div/div/div/select</value>
      <webElementGuid>7455bbe0-652e-4d4a-b893-283747cb6751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospital Details:'])[1]/following::select[1]</value>
      <webElementGuid>946971e4-2801-42a1-ada4-8fcba17c8901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to copy Permanent Address data'])[1]/following::select[4]</value>
      <webElementGuid>903faa6a-4972-427e-b6f1-cc3a60023b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I confirm that I have read and understood the terms of use of Mango Cancer Care PBP programme.'])[1]/preceding::select[4]</value>
      <webElementGuid>008be3e7-bf4b-4058-a5f6-b8f8695f5914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div/select</value>
      <webElementGuid>15ac7799-5dff-4404-87f3-2821dbcc385e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'diagnosis' and (text() = 'Select DiagnosisNon-small Cell Lung CancerBreast CancerHead &amp; Neck Cancer' or . = 'Select DiagnosisNon-small Cell Lung CancerBreast CancerHead &amp; Neck Cancer')]</value>
      <webElementGuid>74401844-3351-46c2-973d-31fb9c12649d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
