<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select CityAmbalaAsandhAteli MandiBa_a68b53</name>
   <tag></tag>
   <elementGuidId>951dbc22-c88a-42c4-9bb3-1f1e6c1722b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4fcf92cd-648a-4df1-945e-8ec8e3e6b375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>76e3bac3-9c80-49ad-a542-c8105781269a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>614830bd-2257-4ede-8c0d-80488d4cd56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4222a555-d255-4fba-89c3-f71031c42155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CityAmbalaAsandhAteli MandiBahadurgarhBara UchanaBarwalaBawalBeri KhasBhiwaniBilaspurBuriyaCharkhi DadriChhachhrauliDabwaliDharuheraEllenabadFaridabadFaridabad DistrictFarrukhnagarFatehabadFatehabad DistrictFirozpur JhirkaGharaundaGohanaGorakhpurGurgaonHansiHasanpurHisarHodalInda ChhoiIndriJagadhriJakhalJhajjarJindKaithalKalanaurKalanwaliKanina KhasKarnalKharkhaudaKheri SamplaKurukshetraLadwaLoharuMahamMahendragarhMandholi KalanMustafabadNarayangarhNarnaulNarnaundNarwanaNilokheriNuhPalwalPanchkulaPanipatPataudiPehowaPinjaurPunahanaPundriRadaurRaniaRatiaRewariRewari DistrictRohtakSafidonSamalkhaShadipur JulanaShahabadSirsaSohnaSonipatTaoruThanesarTohanaToshamUklanaYamunanagar</value>
      <webElementGuid>a55bcb30-72c8-4ad8-9f5b-79fc72d978e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;login-main&quot;]/div[2]/div[@class=&quot;reg-container self d-flex justify-content-center align-items-center  container&quot;]/div[@class=&quot;reg-box d-flex flex-column&quot;]/form[1]/fieldset[2]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col&quot;]/div[1]/select[@id=&quot;city&quot;]</value>
      <webElementGuid>5c6fa23e-ffd6-46d5-b0fa-083956334795</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>8794f4ee-a2e0-4ea8-95b2-44eee2cdfb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/fieldset[2]/div[2]/div[2]/div/select</value>
      <webElementGuid>83937832-2c35-4fd2-8922-50eb2a547c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details:'])[1]/following::select[4]</value>
      <webElementGuid>db5d0485-dd68-4f00-abab-e4fbeff9fe3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to copy Permanent Address data'])[1]/preceding::select[1]</value>
      <webElementGuid>4f71c61c-691b-4bdc-b8de-570ddd67c150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospital Details:'])[1]/preceding::select[4]</value>
      <webElementGuid>250c120c-86db-4d88-8422-1996b080d2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/select</value>
      <webElementGuid>a9294462-de31-4eae-8a2c-18c04136746f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'City' and @id = 'city' and (text() = 'Select CityAmbalaAsandhAteli MandiBahadurgarhBara UchanaBarwalaBawalBeri KhasBhiwaniBilaspurBuriyaCharkhi DadriChhachhrauliDabwaliDharuheraEllenabadFaridabadFaridabad DistrictFarrukhnagarFatehabadFatehabad DistrictFirozpur JhirkaGharaundaGohanaGorakhpurGurgaonHansiHasanpurHisarHodalInda ChhoiIndriJagadhriJakhalJhajjarJindKaithalKalanaurKalanwaliKanina KhasKarnalKharkhaudaKheri SamplaKurukshetraLadwaLoharuMahamMahendragarhMandholi KalanMustafabadNarayangarhNarnaulNarnaundNarwanaNilokheriNuhPalwalPanchkulaPanipatPataudiPehowaPinjaurPunahanaPundriRadaurRaniaRatiaRewariRewari DistrictRohtakSafidonSamalkhaShadipur JulanaShahabadSirsaSohnaSonipatTaoruThanesarTohanaToshamUklanaYamunanagar' or . = 'Select CityAmbalaAsandhAteli MandiBahadurgarhBara UchanaBarwalaBawalBeri KhasBhiwaniBilaspurBuriyaCharkhi DadriChhachhrauliDabwaliDharuheraEllenabadFaridabadFaridabad DistrictFarrukhnagarFatehabadFatehabad DistrictFirozpur JhirkaGharaundaGohanaGorakhpurGurgaonHansiHasanpurHisarHodalInda ChhoiIndriJagadhriJakhalJhajjarJindKaithalKalanaurKalanwaliKanina KhasKarnalKharkhaudaKheri SamplaKurukshetraLadwaLoharuMahamMahendragarhMandholi KalanMustafabadNarayangarhNarnaulNarnaundNarwanaNilokheriNuhPalwalPanchkulaPanipatPataudiPehowaPinjaurPunahanaPundriRadaurRaniaRatiaRewariRewari DistrictRohtakSafidonSamalkhaShadipur JulanaShahabadSirsaSohnaSonipatTaoruThanesarTohanaToshamUklanaYamunanagar')]</value>
      <webElementGuid>0315c9bc-3fa8-4dd4-8da7-44866a171fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
