<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GenderMaleFemale</name>
   <tag></tag>
   <elementGuidId>ec4cd04b-a713-4cad-a8fd-9f4d8cacaca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div/form/fieldset/div[2]/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>12a31d5f-fb83-412a-8b16-6ea0297e394f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7d3bd88c-691f-4eae-971d-1ba0acf705ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GenderMaleFemale</value>
      <webElementGuid>4f186630-bb86-4228-8bb8-52573ef82770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;login-main&quot;]/div[2]/div[@class=&quot;reg-container self d-flex justify-content-center align-items-center  container&quot;]/div[@class=&quot;reg-box d-flex flex-column&quot;]/form[1]/fieldset[@class=&quot;false&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[1]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>d1fa59e4-30ad-4b27-a328-6c34226f8692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div/form/fieldset/div[2]/div/div/select</value>
      <webElementGuid>d1f96e6c-0d2d-4972-84e9-d7466be5de2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details:'])[1]/following::select[1]</value>
      <webElementGuid>2bf23fe8-6832-4e55-85f1-dfee133f7ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to copy Permanent Address data'])[1]/preceding::select[4]</value>
      <webElementGuid>d61d8d5e-3031-4e5c-8ecd-dc3e4f6d9160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>337a7339-3f32-4e12-8971-bee684173c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'GenderMaleFemale' or . = 'GenderMaleFemale')]</value>
      <webElementGuid>01425359-df2b-4ef9-b371-62a972123bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
