<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PBP Program</name>
   <tag></tag>
   <elementGuidId>88a9cb42-d626-4440-ab69-1d3fc9fbf669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='custom-side-bar-patient']/div[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb734397-1f23-4fed-b680-6bacfd9b0f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PBP Program</value>
      <webElementGuid>1354104b-b1a6-4f13-9912-eb5a749d714b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-side-bar-patient&quot;)/div[@class=&quot;false accordion-item&quot;]/a[@class=&quot;d-flex justify-content-between align-items-center accordion-button collapsed nav-link&quot;]/span[1]</value>
      <webElementGuid>8e9ec1e9-ca2c-4b36-a934-fe8b89cc8b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d929ab3c-4fc9-4149-b311-b4303577423f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-text  </value>
      <webElementGuid>7b793f45-3e62-4ae1-99e2-56a79dea3ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PBP Program</value>
      <webElementGuid>3676d53d-70dc-4e9e-a649-089d5661c951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-side-bar-patient&quot;)/div[@class=&quot;false accordion-item&quot;]/a[@class=&quot;d-flex justify-content-between align-items-center accordion-button collapsed nav-link&quot;]/span[1]/span[@class=&quot;sidebar-text&quot;]</value>
      <webElementGuid>13d58363-a395-4bfd-b315-2ebac25ac32d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-side-bar-patient']/div[5]/a/span</value>
      <webElementGuid>d2deb4ff-b445-4210-a941-7eac8950f9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinical Notes'])[1]/following::span[1]</value>
      <webElementGuid>a9809b61-034c-401e-b253-eec65b64e7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Treatment'])[1]/following::span[4]</value>
      <webElementGuid>10df3687-e0a0-415d-a16a-c7c6f1724b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/preceding::span[3]</value>
      <webElementGuid>553810ed-5097-4bf6-9da8-44971d1c7343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/span</value>
      <webElementGuid>e9037808-7110-4b21-b5ea-17bb6d764f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PBP Program' or . = 'PBP Program')]</value>
      <webElementGuid>64fcc367-fde3-4869-afb3-8164080cf00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-side-bar-patient']/div[5]/a/span/span[2]</value>
      <webElementGuid>37ff7186-5469-47fe-a777-52283bf9a4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clinical Notes'])[1]/following::span[3]</value>
      <webElementGuid>37fa75ad-41db-4829-8c6a-6ce64db1fc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Treatment'])[1]/following::span[6]</value>
      <webElementGuid>fe32b7ab-9f14-4ddc-8ade-c0a942729eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/preceding::span[1]</value>
      <webElementGuid>8541b7cd-3039-4102-b5b7-4e72056af9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicants'])[1]/preceding::span[3]</value>
      <webElementGuid>0b3fc8a9-dbda-4a24-8586-94e42aae2a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PBP Program']/parent::*</value>
      <webElementGuid>4b4191fb-7b46-43d0-b31f-37a12f79f474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/span/span[2]</value>
      <webElementGuid>d638f351-a5ea-4cab-b091-713e40851ce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
