<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout</name>
   <tag></tag>
   <elementGuidId>c59fff5f-1070-4e74-8550-34d56d2a8f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/nav/div/div/div[2]/div[2]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fw-normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e718f1e1-de16-47db-8a22-892d3168fa3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-normal</value>
      <webElementGuid>f62956e4-1ed1-4438-be3b-46c3cb77d78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>7f9b9ed1-8169-4f5a-be9b-b956a8dedd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/nav[@class=&quot;vbcnavbar  navbar navbar-expand navbar-dark&quot;]/div[@class=&quot;px-0 container-fluid&quot;]/div[@class=&quot;d-flex justify-content-between w-100&quot;]/div[@class=&quot;align-items-center d-none d-md-flex navbar-nav&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;px-0&quot;]/a[@class=&quot;fw-bold d-none d-sm-block dropdown-item&quot;]/span[@class=&quot;fw-normal&quot;]</value>
      <webElementGuid>c043b42e-6cae-4a04-859f-afb84f7b36bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c6815d3d-ef13-4fa2-9037-900cd34d6ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-normal</value>
      <webElementGuid>416ae33b-2639-4a52-849a-361bb8ed7dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>2e9ecced-8fff-419f-b761-a491463814f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/nav[@class=&quot;vbcnavbar  navbar navbar-expand navbar-dark&quot;]/div[@class=&quot;px-0 container-fluid&quot;]/div[@class=&quot;d-flex justify-content-between w-100&quot;]/div[@class=&quot;align-items-center d-none d-md-flex navbar-nav&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;px-0&quot;]/a[@class=&quot;fw-bold d-none d-sm-block dropdown-item&quot;]/span[@class=&quot;fw-normal&quot;]</value>
      <webElementGuid>d15f2e91-00b9-4a8e-b349-fccbf5dc92cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1454858c-b1f8-4233-9e98-35b9e24538dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-normal</value>
      <webElementGuid>aa8519c8-612c-475d-8d4e-04226d3c628e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>6516bcdf-7734-46f2-966e-8a6598544341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/nav[@class=&quot;vbcnavbar  navbar navbar-expand navbar-dark&quot;]/div[@class=&quot;px-0 container-fluid&quot;]/div[@class=&quot;d-flex justify-content-between w-100&quot;]/div[@class=&quot;align-items-center d-none d-md-flex navbar-nav&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;px-0&quot;]/a[@class=&quot;fw-bold d-none d-sm-block dropdown-item&quot;]/span[@class=&quot;fw-normal&quot;]</value>
      <webElementGuid>c13d9aac-5e8e-4570-97e9-5d015eb318df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b40272b-8b51-47c0-abeb-1eb495fca270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-normal</value>
      <webElementGuid>5b9658ab-0807-4f14-b05a-cd20aff30a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>62cc2801-1292-40fb-90d5-8bca618097de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;content&quot;]/nav[@class=&quot;vbcnavbar  navbar navbar-expand navbar-dark&quot;]/div[@class=&quot;px-0 container-fluid&quot;]/div[@class=&quot;d-flex justify-content-between w-100&quot;]/div[@class=&quot;align-items-center d-none d-md-flex navbar-nav&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;px-0&quot;]/a[@class=&quot;fw-bold d-none d-sm-block dropdown-item&quot;]/span[@class=&quot;fw-normal&quot;]</value>
      <webElementGuid>b8d8ffb3-e7a8-470d-913b-9c7ac9fce282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/nav/div/div/div[2]/div[2]/div/a/span</value>
      <webElementGuid>de80e390-b4ef-4552-9394-b0c361e273ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sukesh M'])[1]/following::span[4]</value>
      <webElementGuid>c13287a6-134d-48bb-9f28-407ef1403223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome'])[1]/following::span[5]</value>
      <webElementGuid>af55ff50-dc00-41c6-bf30-0e471206d326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::span[1]</value>
      <webElementGuid>9f183845-9cb5-4c04-a09e-0e12f22896d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PBP Program'])[2]/preceding::span[2]</value>
      <webElementGuid>7e9b2700-8a00-4cf7-815e-2eaa89f435e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>e08ecdc9-62e9-4dcd-ade8-aad2291b85f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>38bd1167-ae02-4b9d-a0fe-d421f9371c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>45a55e68-8872-4446-8b61-a994242634c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cycle Details 0/12'])[2]/following::span[3]</value>
      <webElementGuid>69a70b27-8426-4466-9d23-c6abc7ef6131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Treatment on Tagrisso-Osimertinib,'])[1]/following::span[4]</value>
      <webElementGuid>e486e995-0ae7-4572-89b9-c82881ede03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cycle Details 3/12'])[2]/following::span[3]</value>
      <webElementGuid>efa2c4d7-f920-4eaa-aad5-24fe3899049e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::span[2]</value>
      <webElementGuid>b1260839-b835-47e4-9b7f-390d65641b13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
